// <auto-generated />
using System;
using Buckeye.Lending.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Buckeye.Lending.Api.Migrations
{
    [DbContext(typeof(LendingContext))]
    [Migration("20260312221907_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Buckeye.Lending.Api.Models.Applicant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Applicants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "sarah.johnson@email.com",
                            Name = "Sarah Johnson",
                            Phone = "614-555-0101"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 1, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "michael.chen@email.com",
                            Name = "Michael Chen",
                            Phone = "614-555-0102"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "emily.rodriguez@email.com",
                            Name = "Emily Rodriguez",
                            Phone = "614-555-0103"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2026, 1, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "david.kim@email.com",
                            Name = "David Kim",
                            Phone = "614-555-0104"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "jessica.martinez@email.com",
                            Name = "Jessica Martinez",
                            Phone = "614-555-0105"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "james.wilson@email.com",
                            Name = "James Wilson",
                            Phone = "614-555-0106"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "amanda.foster@email.com",
                            Name = "Amanda Foster",
                            Phone = "614-555-0107"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2026, 2, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "robert.taylor@email.com",
                            Name = "Robert Taylor",
                            Phone = "614-555-0108"
                        });
                });

            modelBuilder.Entity("Buckeye.Lending.Api.Models.LoanApplicationDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AnnualIncome")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("ApplicantId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApplicantName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LoanAmount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("LoanTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("RiskRating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SubmittedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantId");

                    b.HasIndex("LoanTypeId");

                    b.ToTable("LoanApplications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnnualIncome = 95000m,
                            ApplicantId = 1,
                            ApplicantName = "Sarah Johnson",
                            LoanAmount = 250000m,
                            LoanTypeId = 1,
                            Notes = "Strong credit history, stable employment 8 years",
                            RiskRating = 2,
                            Status = "Approved",
                            SubmittedDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            AnnualIncome = 68000m,
                            ApplicantId = 2,
                            ApplicantName = "Michael Chen",
                            LoanAmount = 32500m,
                            LoanTypeId = 2,
                            Notes = "First-time auto loan, good income-to-debt ratio",
                            RiskRating = 3,
                            Status = "Pending",
                            SubmittedDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            AnnualIncome = 72000m,
                            ApplicantId = 3,
                            ApplicantName = "Emily Rodriguez",
                            LoanAmount = 320000m,
                            LoanTypeId = 1,
                            Notes = "Income-to-loan ratio exceeds threshold",
                            RiskRating = 5,
                            Status = "Denied",
                            SubmittedDate = new DateTime(2026, 1, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            AnnualIncome = 52000m,
                            ApplicantId = 4,
                            ApplicantName = "David Kim",
                            LoanAmount = 15000m,
                            LoanTypeId = 3,
                            Notes = "Consolidating credit card debt, excellent history",
                            RiskRating = 2,
                            Status = "Approved",
                            SubmittedDate = new DateTime(2026, 2, 3, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            AnnualIncome = 150000m,
                            ApplicantId = 5,
                            ApplicantName = "Jessica Martinez",
                            LoanAmount = 500000m,
                            LoanTypeId = 4,
                            Notes = "New restaurant venture, limited business credit",
                            RiskRating = 4,
                            Status = "Under Review",
                            SubmittedDate = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            AnnualIncome = 75000m,
                            ApplicantId = 6,
                            ApplicantName = "James Wilson",
                            LoanAmount = 28000m,
                            LoanTypeId = 2,
                            Notes = "Repeat customer, excellent credit score 780+",
                            RiskRating = 1,
                            Status = "Approved",
                            SubmittedDate = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            AnnualIncome = 88000m,
                            ApplicantId = 7,
                            ApplicantName = "Amanda Foster",
                            LoanAmount = 175000m,
                            LoanTypeId = 1,
                            Notes = "First-time homebuyer, pending employment verification",
                            RiskRating = 3,
                            Status = "Pending",
                            SubmittedDate = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            AnnualIncome = 120000m,
                            ApplicantId = 8,
                            ApplicantName = "Robert Taylor",
                            LoanAmount = 75000m,
                            LoanTypeId = 4,
                            Notes = "Insufficient collateral for requested amount",
                            RiskRating = 4,
                            Status = "Denied",
                            SubmittedDate = new DateTime(2026, 2, 8, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Buckeye.Lending.Api.Models.LoanNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("LoanApplicationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LoanApplicationId");

                    b.ToTable("LoanNotes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Loan Officer",
                            CreatedDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            LoanApplicationId = 1,
                            Text = "Strong credit history, stable employment 8 years"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Underwriter",
                            CreatedDate = new DateTime(2026, 1, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            LoanApplicationId = 1,
                            Text = "Approved — meets all DTI requirements"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Underwriter",
                            CreatedDate = new DateTime(2026, 1, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            LoanApplicationId = 3,
                            Text = "Income-to-loan ratio exceeds 4.5x threshold"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Loan Officer",
                            CreatedDate = new DateTime(2026, 2, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            LoanApplicationId = 5,
                            Text = "New restaurant venture — requesting additional financials"
                        });
                });

            modelBuilder.Entity("Buckeye.Lending.Api.Models.LoanPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("LoanApplicationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LoanApplicationId");

                    b.ToTable("LoanPayments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 1450.00m,
                            LoanApplicationId = 1,
                            Method = "ACH",
                            PaymentDate = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Amount = 325.00m,
                            LoanApplicationId = 4,
                            Method = "ACH",
                            PaymentDate = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Amount = 475.00m,
                            LoanApplicationId = 6,
                            Method = "Check",
                            PaymentDate = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Buckeye.Lending.Api.Models.LoanType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxTermMonths")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LoanTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Home purchase or refinance loan",
                            MaxTermMonths = 360,
                            Name = "Mortgage"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Vehicle purchase loan",
                            MaxTermMonths = 84,
                            Name = "Auto"
                        },
                        new
                        {
                            Id = 3,
                            Description = "General-purpose unsecured loan",
                            MaxTermMonths = 60,
                            Name = "Personal"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Small business or startup loan",
                            MaxTermMonths = 120,
                            Name = "Business"
                        });
                });

            modelBuilder.Entity("Buckeye.Lending.Api.Models.LoanApplicationDto", b =>
                {
                    b.HasOne("Buckeye.Lending.Api.Models.Applicant", "Applicant")
                        .WithMany("LoanApplications")
                        .HasForeignKey("ApplicantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Buckeye.Lending.Api.Models.LoanType", "LoanType")
                        .WithMany("LoanApplications")
                        .HasForeignKey("LoanTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Applicant");

                    b.Navigation("LoanType");
                });

            modelBuilder.Entity("Buckeye.Lending.Api.Models.LoanNote", b =>
                {
                    b.HasOne("Buckeye.Lending.Api.Models.LoanApplicationDto", "LoanApplication")
                        .WithMany("LoanNotes")
                        .HasForeignKey("LoanApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoanApplication");
                });

            modelBuilder.Entity("Buckeye.Lending.Api.Models.LoanPayment", b =>
                {
                    b.HasOne("Buckeye.Lending.Api.Models.LoanApplicationDto", "LoanApplication")
                        .WithMany("Payments")
                        .HasForeignKey("LoanApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoanApplication");
                });

            modelBuilder.Entity("Buckeye.Lending.Api.Models.Applicant", b =>
                {
                    b.Navigation("LoanApplications");
                });

            modelBuilder.Entity("Buckeye.Lending.Api.Models.LoanApplicationDto", b =>
                {
                    b.Navigation("LoanNotes");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Buckeye.Lending.Api.Models.LoanType", b =>
                {
                    b.Navigation("LoanApplications");
                });
#pragma warning restore 612, 618
        }
    }
}
